name: Build WASM Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    if: github.ref_type == 'tag' && startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Fetch main branch
        run: git fetch origin main

      - name: Verify tag targets main
        run: |
          if ! git merge-base --is-ancestor "$GITHUB_SHA" origin/main; then
            echo "Tag must reference a commit on main." >&2
            exit 1
          fi

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Build WASM image
        run: docker build -t capstone-wasm -f Dockerfile .

      - name: Extract WASM artifact
        run: |
          rm -rf dist
          docker build --target artifact -f Dockerfile --output type=local,dest=dist .

      - name: Determine release tag
        id: release_tag
        run: |
          tag="${GITHUB_REF#refs/tags/}"
          echo "tag=$tag" >> "$GITHUB_OUTPUT"

      - name: Ensure release exists
        run: |
          tag="${{ steps.release_tag.outputs.tag }}"
          gh release view "$tag" >/dev/null 2>&1 || gh release create "$tag" --notes ""

      - name: Upload WASM to release
        run: gh release upload "${{ steps.release_tag.outputs.tag }}" dist/libcapstone.wasm --clobber
